server:
  port: 8090    
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: artists
        uri: lb://artists
        predicates:
        - Path=/api/artists/**
      - id: customer
        uri: lb://customer
        predicates:
        - Path:/api/customer/**
      - id: events
        uri: lb://events
        predicates:
        - Path=/api/events/**